[theme]
base = "dark"
primaryColor = "#FFFFFF"                # Akzente in Wei√ü
backgroundColor = "#0E1117"             # Fast Schwarz
secondaryBackgroundColor = "#262730"    # Dunkelgrau
textColor = "#FAFAFA"